<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="DESKTOP-RLDEJ0K"><DocLocation><![CDATA[C:\Users\Lenovo\Documents\keyworddrivenframework\Driver\Driver1]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Driver1]]></DName>
<Res><![CDATA[Res17]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[tr1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "tr1" started.]]></Details>
<Time><![CDATA[30-03-2022 - 09:12:13]]></Time>
<TimeTick>1648611733</TimeTick>
<NodeArgs eType="Transaction" icon="5" nRep="8" nType="Start Transaction" Source="Action1" SourceLine="0" >
<Disp><![CDATA[tr1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[30-03-2022 - 09:13:05]]></Time>
<TimeTick>1648611785</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Details>
<Time><![CDATA[30-03-2022 - 09:13:05]]></Time>
<TimeTick>1648611785</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[30-03-2022 - 09:13:06]]></Time>
<TimeTick>1648611786</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[30-03-2022 - 09:13:06]]></Time>
<TimeTick>1648611786</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="15" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 09:13:37]]></Time>
<TimeTick>1648611817</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[agentName]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"agentName"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 09:13:37]]></Time>
<TimeTick>1648611817</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 09:13:37]]></Time>
<TimeTick>1648611817</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="61" status="Warning" nType="Parent description" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="60" status="Failed" nType="Run Error" >
<Disp><![CDATA[agentName]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="59" status="Failed" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 09:13:38]]></Time>
<TimeTick>1648611818</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;agentName&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl<BR/>Line (6): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfEdit(&quot;agentName&quot;).Set &quot;john&quot;&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 09:13:38]]></Time>
<TimeTick>1648611818</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="63" status="Failed" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[password]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"password"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 09:14:01]]></Time>
<TimeTick>1648611841</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:00]]></Time>
<TimeTick>1648611900</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="103" status="Warning" nType="Parent description" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="102" status="Failed" nType="Run Error" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[password]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="62" status="Failed" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:00]]></Time>
<TimeTick>1648611900</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;password&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl<BR/>Line (7): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfEdit(&quot;password&quot;).Set &quot;hp&quot;&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:00]]></Time>
<TimeTick>1648611900</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="105" status="Failed" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="6" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"OK"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:22]]></Time>
<TimeTick>1648611922</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:22]]></Time>
<TimeTick>1648611922</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="154" status="Warning" nType="Parent description" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="153" status="Failed" nType="Run Error" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[OK]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="104" status="Failed" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:22]]></Time>
<TimeTick>1648611922</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;OK&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl<BR/>Line (8): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfButton(&quot;OK&quot;).Click&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:22]]></Time>
<TimeTick>1648611922</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="156" status="Failed" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="7" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:23]]></Time>
<TimeTick>1648611923</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="158" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="155" status="Failed" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login unSuccessful]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:23]]></Time>
<TimeTick>1648611923</TimeTick>
<NodeArgs eType="User" icon="11" nRep="159" status="Failed" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:26]]></Time>
<TimeTick>1648611926</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[The&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;object's&nbsp;description&nbsp;matches&nbsp;more&nbsp;than&nbsp;one&nbsp;of&nbsp;the&nbsp;objects&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.&nbsp;Add&nbsp;additional&nbsp;properties&nbsp;to&nbsp;the&nbsp;object&nbsp;description&nbsp;in&nbsp;order&nbsp;to&nbsp;uniquely&nbsp;identify&nbsp;the&nbsp;object.]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:26]]></Time>
<TimeTick>1648611926</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:26]]></Time>
<TimeTick>1648611926</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="164" status="Warning" nType="Description" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="163" status="Failed" nType="Run Error" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="162" status="Failed" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:26]]></Time>
<TimeTick>1648611926</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;HPE MyFlight Sample Applicatio&quot; object's description matches more than one of the objects currently displayed in your application. Add additional properties to the object description in order to uniquely identify the object.<BR/>Function file: C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl<BR/>Line (18): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).Close&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:26]]></Time>
<TimeTick>1648611926</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="166" status="Failed" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="17" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[The&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;object's&nbsp;description&nbsp;matches&nbsp;more&nbsp;than&nbsp;one&nbsp;of&nbsp;the&nbsp;objects&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.&nbsp;Add&nbsp;additional&nbsp;properties&nbsp;to&nbsp;the&nbsp;object&nbsp;description&nbsp;in&nbsp;order&nbsp;to&nbsp;uniquely&nbsp;identify&nbsp;the&nbsp;object.]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:26]]></Time>
<TimeTick>1648611926</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:26]]></Time>
<TimeTick>1648611926</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="168" status="Warning" nType="Description" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="167" status="Failed" nType="Run Error" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:26]]></Time>
<TimeTick>1648611926</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="170" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="165" status="Failed" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[Closeapp]]></Obj>
<Details ><![CDATA[Closeapp unSuccessful]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:26]]></Time>
<TimeTick>1648611926</TimeTick>
<NodeArgs eType="User" icon="11" nRep="171" status="Passed" Source="C:\Users\Lenovo\Documents\keyworddrivenframework\FunctionalLibrary\Frame.qfl" SourceLine="-1" >
<Disp><![CDATA[Closeapp]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:39]]></Time>
<TimeTick>1648611939</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:39]]></Time>
<TimeTick>1648611939</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="175" status="Passed" >
<Disp><![CDATA[Run ""C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe"",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="174" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:39]]></Time>
<TimeTick>1648611939</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:39]]></Time>
<TimeTick>1648611939</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="179" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HPE\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="178" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:39]]></Time>
<TimeTick>1648611939</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[agentName]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"agentName"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:39]]></Time>
<TimeTick>1648611939</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 09:15:40]]></Time>
<TimeTick>1648611940</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="182" status="Warning" nType="Parent description" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="181" status="Failed" nType="Run Error" >
<Disp><![CDATA[agentName]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[30-03-2022 - 09:16:04]]></Time>
<TimeTick>1648611964</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="215" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[password]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"password"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 09:16:04]]></Time>
<TimeTick>1648611964</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 09:16:04]]></Time>
<TimeTick>1648611964</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="217" status="Warning" nType="Parent description" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="216" status="Failed" nType="Run Error" >
<Disp><![CDATA[password]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[30-03-2022 - 09:16:04]]></Time>
<TimeTick>1648611964</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="219" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"OK"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 09:16:04]]></Time>
<TimeTick>1648611964</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 09:16:04]]></Time>
<TimeTick>1648611964</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="221" status="Warning" nType="Parent description" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="220" status="Failed" nType="Run Error" >
<Disp><![CDATA[OK]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[30-03-2022 - 09:16:05]]></Time>
<TimeTick>1648611965</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="223" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[30-03-2022 - 09:16:05]]></Time>
<TimeTick>1648611965</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="224" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="180" status="Failed" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[30-03-2022 - 09:16:05]]></Time>
<TimeTick>1648611965</TimeTick>
<NodeArgs eType="User" icon="11" nRep="225" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 09:16:59]]></Time>
<TimeTick>1648612019</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["SEARCH ORDER"]]></Details>
<Time><![CDATA[30-03-2022 - 09:16:59]]></Time>
<TimeTick>1648612019</TimeTick>